# Generated by Django 2.2.2 on 2020-05-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbooking', '0002_newconnection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newconnection',
            name='status',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
