# Generated by Django 2.2.2 on 2020-05-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbooking', '0004_auto_20200526_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcylinder',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
